name: 'Swanks & Sons '
favicon: null
layout_spectrum: 0.7716839746572077
typography_spectrum: 0.4629274813923985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f0304'
    - '#a9a9a7'
    - '#dcdcdc'
    - '#777777'
    - '#444243'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
